### PR TITLE
update style and enable linters

### PR DESCRIPTION
**Pull request by dirk-thomas**
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/1862/)
* OS X [Build Status](http://ci.ros2.org/job/ci_osx/1397/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/1780/)

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Ready for review.

**Comment by wjwwood** [comment]
LGTM too, I'd suggest making code best practice changes separately (other than maybe use of `{}` blocks), so that they are easier to review. For example, which C++ style cast you use instead of the catch all C style cast should be reviewed carefully in each case. And it's easier to do that without the whitespace changes.

**Comment by dirk-thomas** [comment]
@mikaelarguedas I haven't seen `(T * t)` in the diff anywhere. I only touched the code which is now being linted and needed update. Please feel free to create a follow up PR to add linting to additional parts.

@wjwwood I agree that it would be nicer to have smaller easier to review pieces. In this case the code was so different from our style that the changes are significant. Splitting those up would have required more time. The diff can easily be searched for e.g. `_cast<` in order to review those cases. I used `static_cast` when going from a `void *` to `Something *` and `reinterpret_cast` in the other remaining cases.

**Comment by mikaelarguedas** [comment]
@dirk-thomas agreed it can definitely be addressed on a separate PR, hence the approval. I was just curious when I saw all these `(T *)` while reviewing and wasn't sure if I should act on it (and if the linters were supposed to catch it), hence the question. I'll open a follow-up PR to address them

**Pull request merged**
